"""add temp column

Revision ID: 9cdb21fca13f
Revises: cb06222389d2
Create Date: 2020-04-27 18:39:22.171396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cdb21fca13f'
down_revision = 'cb06222389d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('temp', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'temp')
    # ### end Alembic commands ###
